server:
  port: 8001
spring:
  application:
    name: Cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://116.62.212.51:3306/test_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: zezo
    password: Zezo@123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zezo.springcloud.bo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true